spring:
  application:
    name: pedritopos-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/pedritopos
    username: pedritopos
    password: pedritopos123

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: "OP=cF$6n^8c6£GN0(06<6Uiv0DLg]EQ~"
  expiration-ms: 28800000  # 8 horas
  refresh-expiration-ms: 604800000  # 7 días

server:
  port: 8080
